#---------------------------------------------------#
## 配置文件需要放置在 $HOME/.config/clash/*.yaml

## 这份文件是clashX的基础配置文件，请尽量新建配置文件进行修改。
## 端口设置请在 菜单条图标->配置->更多配置 中进行修改

## 如果您不知道如何操作，请参阅 官方Github文档 https://dreamacro.github.io/clash/
#---------------------------------------------------#

mode: rule
log-level: info

proxies:
#  - name: "Trojan-Go Server"
#    type: trojan
#    server: jpv1.aninja.cc        # 替换为你的服务器域名或 IP
#    port: 37117                  # 替换为你的 Trojan-Go 服务端端口
#    password: "Vx7bhy4RIY"  # 替换为你的 Trojan-Go 密码
#    sni: "jpv1.aninja.cc"         # 替换为你的服务器域名
#    skip-cert-verify: true     # 如果使用自签名证书，设置为 true
#    network: tcp                # WebSocket 传输协议

  - name: "sv.aninja.cc"
    type: trojan
    server: sv.aninja.cc        # 替换为你的服务器域名或 IP
    port: 12345                  # 替换为你的 Trojan-Go 服务端端口
    password: "Aa505814."  # 替换为你的 Trojan-Go 密码
    sni: "sv.aninja.cc"         # 替换为你的服务器域名
    network: ws
    ws-opts:
      path: /ws
      headers:
        Host: sv.aninja.cc

  - name: "la.aninja.cc"
    type: trojan
    server: la.aninja.cc        # 替换为你的服务器域名或 IP
    port: 12345                  # 替换为你的 Trojan-Go 服务端端口
    password: "admin123"  # 替换为你的 Trojan-Go 密码
    sni: "la.aninja.cc"         # 替换为你的服务器域名
    network: tcp

proxy-groups:
  - name: "Proxy"
    type: select
    proxies:
      - "sv.aninja.cc"
      - "la.aninja.cc"
      - "DIRECT"

rules:
  - DOMAIN-SUFFIX,google.com,Proxy
  - MATCH,Proxy
