#---------------------------------------------------#
## 配置文件需要放置在 $HOME/.config/clash/*.yaml

## 这份文件是clashX的基础配置文件，请尽量新建配置文件进行修改。
## 端口设置请在 菜单条图标->配置->更多配置 中进行修改

## 如果您不知道如何操作，请参阅 官方Github文档 https://dreamacro.github.io/clash/
#---------------------------------------------------#

mode: rule
log-level: info

proxies:
  - name: "Trojan-Go Server"
    type: trojan
    server: jpv1.aninja.cc        # 替换为你的服务器域名或 IP
    port: 37117                  # 替换为你的 Trojan-Go 服务端端口
    password: "Vx7bhy4RIY"  # 替换为你的 Trojan-Go 密码
    sni: "jpv1.aninja.cc"         # 替换为你的服务器域名
    skip-cert-verify: true     # 如果使用自签名证书，设置为 true
    network: tcp                # WebSocket 传输协议

  - name: "Trojan-Go CDN"
    type: trojan
    server: sv.aninja.cc
    sni: sv.aninja.cc
    port: 443
    password: "Aa505814."
    tls: true
    udp: true
    cipher: tls
    skip-cert-verify: true
    websocket:
      enable: true
      path: "/ws"

  - name: "sv.aninja.cc-tcp"
    type: trojan
    server: sv.aninja.cc
    port: 443
    password: "Aa505814."
    sni: sv.aninja.cc
    skip-cert-verify: false
    network: tcp
    udp: true


  - name: "sv.aninja.cc"
    type: trojan
    server: sv.aninja.cc        # 替换为你的服务器域名或 IP
    port: 12345                  # 替换为你的 Trojan-Go 服务端端口
    password: "Aa505814."  # 替换为你的 Trojan-Go 密码
    sni: "sv.aninja.cc"         # 替换为你的服务器域名
    network: ws
    ws-opts:
      path: /ws
      headers:
        Host: sv.aninja.cc

  - name: "sv.aninja.cc443"
    type: trojan
    server: sv.aninja.cc        # 替换为你的服务器域名或 IP
    port: 443                  # 替换为你的 Trojan-Go 服务端端口
    password: "Aa505814."  # 替换为你的 Trojan-Go 密码
    sni: "sv.aninja.cc"         # 替换为你的服务器域名
    network: ws
    ws-opts:
      path: /ws
      headers:
        Host: sv.aninja.cc

  - name: "sv.aninja.cc80"
    type: trojan
    server: sv.aninja.cc        # 替换为你的服务器域名或 IP
    port: 80                  # 替换为你的 Trojan-Go 服务端端口
    password: "Aa505814."  # 替换为你的 Trojan-Go 密码
    sni: "sv.aninja.cc"         # 替换为你的服务器域名
    network: ws
    ws-opts:
      path: /ws
      headers:
        Host: sv.aninja.cc
proxy-groups:
  - name: "Proxy"
    type: select
    proxies:
      - "Trojan-Go Server"
      - "sv.aninja.cc"
      - "sv.aninja.cc443"
      - "sv.aninja.cc80"
      - "sv.aninja.cc-tcp"
      - "Trojan-Go CDN"
      - "DIRECT"

rules:
  - DOMAIN-SUFFIX,google.com,Proxy
  - MATCH,Proxy
